repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
    -   id: end-of-file-fixer
        exclude: ^.+/(test/resources|resources/db)/.+$
    -   id: trailing-whitespace
        exclude: ^.+/(test/resources|resources/db)/.+$
-   repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.5.5
    hooks:
    -   id: remove-crlf
        exclude: ^.+/(test/resources|resources/db)/.+$
    -   id: remove-tabs
        args: [ --whitespaces-count=2 ]
        exclude: ^.+/(test/resources|resources/db)/.+$

-   repo: https://github.com/extenda/pre-commit-hooks
    rev: v0.14.0
    hooks:
    -   id: google-java-formatter
